### ISSUE TITLE
base58 encode/decode

### ISSUE THREAD

**Issue by weissjeffm** [amper5and/secrets.js#1]
Would it be possible to add a base58 encode/decode option?

Here's an implementation of the algorithm.
https://gist.github.com/inflammable/2929362

I'm trying to use PassGuardian to split a bitcoin wallet key, and I'd like the resulting output to be as short as possible.  Right now I could still do this myself, taking the base58 key, decoding it to a number, splitting it with the secrets lib, and then base58 encoding the pieces.

However I'd like someone less computer savvy than myself to be able to reassemble the key if I'm not around.

I'll put up a $20 bounty (in bitcoins).  I know that is probably not enough to cover the effort but maybe others will contribute.

**Comment by Perlover** [comment]
+1

**Comment by Perlover** [comment]
Hi, i am ready to pay by Bitcoin (as donation) but can you add this feature near time? :)

**Comment by weissjeffm** [comment]
@Perlover check out http://bitaddress.org

It does what I was originally looking for (under split wallet). I contributed this feature myself, and the bitaddress author cleaned it up a bit.

**Comment by amper5and** [comment]
it requires to many bloated js libraries to come up with something seemingly so simple. I will work on it, but no promises. Alternative (bloated) exist, as mentioned above.
