### ISSUE TITLE
Uh. Doesn't actually appear to be SSS

### ISSUE THREAD

**Issue by gmaxwell** [amper5and/secrets.js#2]
This looks like it's just using a radix-16 RS code?

If so, then I don't think it's information theoretically secure. Classic SSS fixes the whole message in a single field element.

I think just doing an RS code over bytes/shorts results in sub-threshold shares leaking data about linear relationships between different words in the secret.

Do you have a citation for the approach that you're using?

**Comment by amper5and** [comment]
well, that went nowhere. sure wish we had some good testing of secrets.js, but alas just another stray shooter. closing.
